// Regenerates src/api/schema.d.ts from the running API's OpenAPI document.
//   npm run gen:api                      (API on http://127.0.0.1:8000)
//   OCEANEMBED_API=http://host:port npm run gen:api
// The snapshot src/api/openapi.json is committed so a test can check the client against it offline.
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const base = process.env.OCEANEMBED_API ?? "http://127.0.0.1:8000";
const out = (name) => fileURLToPath(new URL(`../src/api/${name}`, import.meta.url));

const res = await fetch(`${base}/api/openapi.json`);
if (!res.ok) throw new Error(`GET ${base}/api/openapi.json -> ${res.status}; is "oceanembed serve" running?`);
const spec = await res.json();
await writeFile(out("openapi.json"), `${JSON.stringify(spec, null, 1)}\n`);
const ast = await openapiTS(spec);
const banner = "// GENERATED by `npm run gen:api` from /api/openapi.json. Do not edit by hand.\n\n";
await writeFile(out("schema.d.ts"), banner + astToString(ast));
console.log(`wrote src/api/openapi.json and src/api/schema.d.ts (${Object.keys(spec.paths).length} paths)`);
